name: wt_radar_chart_examples
description: Example for the wt_radar_chart library
publish_to: 'none' # To publish to pub.dev, remove this line
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

# Scripts to be run with rps
scripts:
  init: flutter pub get
  clean: flutter clean
  refresh: flutter clean; flutter pub get
  test: flutter test
  analise: flutter analyze
  freezed:
    build: dart run build_runner build --delete-conflicting-outputs
  web:
    local_build: flutter build web --release --target lib/main_widgetbook.dart --output ../docs --base-href="/docs/";
    local_serve: (cd ..; open --new http://localhost:8000/docs; python3 -m http.server 8000)
    local_view: open http://localhost:8000/docs;
    build: flutter build web --release --target lib/main_widgetbook.dart --output ../docs --base-href="/wt_radar_chart/" --tree-shake-icons
    view: open --new https://tmcmaster.github.io/wt_radar_chart/

dependencies:
  cupertino_icons: ^1.0.5
  device_preview: ^1.1.0
  firebase_ui_auth: ^1.6.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.3.6
  font_awesome_flutter: ^10.5.0
  freezed: ^2.4.1
  freezed_annotation:
  intl: ^0.19.0
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1
  widgetbook: ^3.1.0
  wt_app_scaffold:
    git:
      url: https://github.com/tmcmaster/wt_app_scaffold.git
  wt_firepod:
    git:
      url: https://github.com/tmcmaster/wt_firepod.git
  wt_logging:
    git:
      url: https://github.com/tmcmaster/wt_logging.git
  wt_models:
    git:
      url: https://github.com/tmcmaster/wt_models.git
  wt_radar_chart:
    path: ..
  wt_widgetbook:
    git:
      url: https://github.com/tmcmaster/wt_widgetbook.git

dev_dependencies:
  build_runner: ^2.4.6
  flutter_lints: ^2.0.2
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/